"""Build the recorded-cost sidecar, once, so nothing after it needs a key.

A recording preserves what the model SAID. It preserves nothing about what
saying it cost, so a replayed ledger came back empty and the cross-rung cost
table could only be regenerated by paying for it a second time. This script
closes that gap: it drives every rung through its recordings, captures the exact
request each one would have sent, and prices the inputs with `count_tokens` -
which generates nothing and bills no output tokens.

Run it once. Commit `tests/recordings/usage.json`. After that the whole
repository, including the cost table, regenerates offline forever.

    python scripts/build_usage.py            # build (needs credentials)
    python scripts/build_usage.py --check    # verify coverage (offline)

TWO HONEST LIMITS, both stated in Chapter 10 and Appendix B rather than buried.

Output counts EXCLUDE THINKING. A recording holds the visible response; on
claude-opus-5 thinking is on by default and is billed as output. So a replayed
output number is a floor, not the bill, and the rows measured live in Chapters 4
through 9 remain the published ones.

Input counts price the structured-output schema as a strict tool, because
`count_tokens` takes no `output_format` and the schema is not small - see
`as_tool` for the calibration. That shape overshoots by roughly ten percent
rather than undershooting by fifty-four, and the residual is close to constant
per call, so it survives being read as a ratio between rungs.

Neither limit is left for the reader to discover: the sidecar records a `source`
per entry, and Appendix B states what a replayed row does and does not include.

`_wire` and `_result_blocks` are imported from the seam rather than reimplemented.
Rebuilding the wire format here would let it drift from the format that was
actually recorded, and a cost file that priced a different request shape than the
one that ran is worse than no cost file.
"""
from __future__ import annotations

import argparse
import inspect
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from escalation_ladder.fixtures.incidents import load_incidents  # noqa: E402
from escalation_ladder.llm import (  # noqa: E402
    MODEL,
    Completion,
    Execute,
    RecordedCompleter,
    ToolRun,
    ToolSpec,
    Usage,
    _result_blocks,
    _wire,
    answer_key,
    prompt_key,
)
from escalation_ladder.rungs import load_all  # noqa: E402

RECORDINGS = Path(__file__).resolve().parent.parent / "tests" / "recordings"
SIDECAR = RECORDINGS / "usage.json"

# One token of content, used to measure what an otherwise empty request costs so
# that framing can be subtracted from an output count. An empty string is not a
# valid message content, so a sentinel is the only way to take this measurement.
_SENTINEL = "x"


def _closed(node: Any) -> Any:
    """Set `additionalProperties: false` on every object in a JSON Schema.

    Pydantic does not emit it and a strict tool is rejected without it. The
    recursion matters: a nested `$defs` entry is an object too, and the API
    checks all of them rather than the top level only.
    """
    if isinstance(node, dict):
        shaped = {key: _closed(value) for key, value in node.items()}
        if shaped.get("type") == "object":
            shaped.setdefault("additionalProperties", False)
        return shaped
    if isinstance(node, list):
        return [_closed(item) for item in node]
    return node


def as_tool(schema: type) -> dict[str, Any]:
    """A structured-output schema priced the way the API actually charges for it.

    `count_tokens` takes no `output_format`, so the schema that a
    `messages.parse` call carries is invisible to it - and on this book's
    smallest rung that schema is over half the request. Sending it as a strict
    tool instead prices the same bytes through the one channel `count_tokens`
    does model.

    Calibrated rather than assumed: on Chapter 4's INC-1042 call, whose live
    mean is 1,098 input tokens, the bare prompt counts 505 and this shape counts
    1,210. A ten percent overshoot from tool framing the real request does not
    pay, against a fifty-four percent undershoot from ignoring the schema
    entirely. The overshoot is roughly constant per call, so it distorts the
    ratios between rungs far less than the omission did - and the ratios are
    what the prose carries.
    """
    return {
        "name": schema.__name__,
        "description": f"Return the {schema.__name__}.",
        "input_schema": _closed(schema.model_json_schema()),
        "strict": True,
    }


@dataclass(frozen=True)
class Request:
    """One vendor request, reconstructed exactly as the recorded run sent it."""

    key: str
    system: str
    messages: list[dict[str, Any]]
    tools: tuple[ToolSpec, ...]
    body: str
    # The structured-output schema, on the requests that carried one. In a tool
    # round only the SECOND request does: the first asks for tools and is given
    # no output shape at all, so pricing a schema into it would invent tokens.
    schema: Any = None


@dataclass
class CapturingCompleter:
    """Replays like `RecordedCompleter` and remembers what it was asked for.

    Capture rather than reconstruction is the point. The recording key is a
    one-way hash, so the prompt that produced it cannot be recovered from the
    file - it has to be re-derived by running the same rung code over the same
    fixtures. That the keys still hit is the proof the re-derivation was exact.
    """

    inner: RecordedCompleter
    seen: dict[str, Request] = field(default_factory=dict)

    def _remember(self, request: Request) -> None:
        # setdefault, not assignment: the same prompt appears under several
        # rungs (Chapter 6's pipeline replays Chapter 4's classification), and
        # it is one request that was billed once.
        self.seen.setdefault(request.key, request)

    def parse(
        self, *, system: str, user: str, schema: type, effort: str = "low"
    ) -> Completion[Any]:
        key = prompt_key(system=system, user=user)
        if key in self.inner.recordings:
            self._remember(
                Request(
                    key=key,
                    system=system,
                    messages=[{"role": "user", "content": user}],
                    tools=(),
                    body=self.inner.recordings[key],
                    schema=schema,
                )
            )
        return self.inner.parse(
            system=system, user=user, schema=schema, effort=effort
        )

    def invoke(
        self,
        *,
        system: str,
        user: str,
        tools: tuple[ToolSpec, ...],
        execute: Execute,
        schema: type,
        effort: str = "low",
    ) -> ToolRun[Any]:
        first = prompt_key(system=system, user=user)
        if first in self.inner.recordings:
            self._remember(
                Request(
                    key=first,
                    system=system,
                    messages=[{"role": "user", "content": user}],
                    tools=tools,
                    body=self.inner.recordings[first],
                )
            )

        run = self.inner.invoke(
            system=system,
            user=user,
            tools=tools,
            execute=execute,
            schema=schema,
            effort=effort,
        )

        # The second request carries the first response and every tool result.
        # Rebuilt from the recorded calls, which is why the assistant turn is
        # assembled here rather than replayed - the recording stores the calls,
        # not the content blocks that wrapped them.
        if run.calls and run.results:
            second = answer_key(system=system, user=user, results=run.results)
            if second in self.inner.recordings:
                assistant = [
                    {
                        "type": "tool_use",
                        "id": call.call_id,
                        "name": call.name,
                        "input": call.arguments,
                    }
                    for call in run.calls
                ]
                self._remember(
                    Request(
                        key=second,
                        system=system,
                        messages=[
                            {"role": "user", "content": user},
                            {"role": "assistant", "content": assistant},
                            {"role": "user", "content": _result_blocks(run.results)},
                        ],
                        tools=tools,
                        body=self.inner.recordings[second],
                        schema=schema,
                    )
                )
        return run


def load_recordings() -> dict[str, str]:
    """Every chapter's recordings, merged.

    Merging is safe because the key IS the prompt: two chapters that send the
    same prompt recorded the same answer, and a collision is therefore an
    identity rather than a conflict.
    """
    merged: dict[str, str] = {}
    for path in sorted(RECORDINGS.glob("ch*.json")):
        merged.update(json.loads(path.read_text(encoding="utf-8")))
    return merged


def capture() -> dict[str, Request]:
    """Drive every rung over every incident and collect the requests."""
    recordings = load_recordings()
    completer = CapturingCompleter(inner=RecordedCompleter(recordings=recordings))
    incidents = load_incidents()

    for rung, fn in load_all().items():
        takes_completer = "completer" in inspect.signature(fn).parameters
        for incident in incidents:
            try:
                if takes_completer:
                    fn(incident, completer)  # type: ignore[call-arg]
                else:
                    fn(incident)  # Level 0 has no seam to pass one through.
            except Exception as exc:  # noqa: BLE001 - a rung failing is data
                print(f"  {rung} failed on {incident.incident_id}: {exc}",
                      file=sys.stderr)
    return completer.seen


def build(client: Any) -> dict[str, dict[str, object]]:
    """Price every captured request with `count_tokens`."""
    framing = client.messages.count_tokens(
        model=MODEL, messages=[{"role": "user", "content": _SENTINEL}]
    ).input_tokens - 1

    sidecar: dict[str, dict[str, object]] = {}
    for key, request in sorted(capture().items()):
        kwargs: dict[str, Any] = {
            "model": MODEL,
            "system": request.system,
            "messages": request.messages,
        }
        wire = [_wire(spec) for spec in request.tools]
        if request.schema is not None:
            wire.append(as_tool(request.schema))
        if wire:
            kwargs["tools"] = wire
        counted = client.messages.count_tokens(**kwargs).input_tokens

        body = client.messages.count_tokens(
            model=MODEL, messages=[{"role": "user", "content": request.body}]
        ).input_tokens
        sidecar[key] = {
            "input_tokens": counted,
            "output_tokens": max(0, body - framing),
            "source": "count_tokens",
        }
    return sidecar


def check() -> int:
    """Offline: does every recorded prompt have a price? Returns an exit code."""
    if not SIDECAR.exists():
        print(f"missing {SIDECAR} - run without --check first", file=sys.stderr)
        return 1
    sidecar = json.loads(SIDECAR.read_text(encoding="utf-8"))
    captured = capture()

    missing = sorted(set(captured) - set(sidecar))
    for key in missing:
        print(f"  no usage recorded for {key}", file=sys.stderr)

    # Recordings this script never reaches are NOT a defect. The cost table
    # walks each rung once per incident at its shipped settings; the depth
    # sweep, the withheld-budget arm, and the --no-quit arm recorded prompts
    # that only exist under settings no rung ships with. Those replay from the
    # same files when their own script runs, and they are priced by nothing
    # here because nothing here asks for them.
    unreached = len(load_recordings()) - len(captured)
    print(f"{len(captured)} prompts on the costed path, {len(sidecar)} priced, "
          f"{len(missing)} missing")
    print(f"{unreached} further recordings belong to the experiment scripts")
    return 1 if missing else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="verify coverage offline instead of building")
    args = parser.parse_args(argv)

    if args.check:
        return check()

    import anthropic  # Imported here so --check stays importable with no SDK.

    sidecar = build(anthropic.Anthropic())
    SIDECAR.parent.mkdir(parents=True, exist_ok=True)
    SIDECAR.write_text(
        json.dumps(sidecar, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"wrote {SIDECAR} ({len(sidecar)} prompts priced)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
